export const imagesArray =      
[
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/0-The-Fool-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Fool'} ,
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/01-The-Magician-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Magician'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/02-The-High-Priestess-Tarot-card-img-182x300-1.jpg.webp',
        name:'The High Priestess'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/03-The-Empress-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Empress'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/04-The-Emperor-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Emperor'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/05-The-Hierophant-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Hierophant'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/06-The-Lovers-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Lovers'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/07-The-Chariot-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Chariot'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/08-Strength-Tarot-card-img-182x300-1.jpg.webp',
        name:'Fortitude'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/09-The-Hermit-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Hermit'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/10-The-Wheel-of-Fortune-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Wheel of Fortune'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/11-Justice-Tarot-card-img-182x300-1.jpg.webp',
        name:'Justice'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/12-The-Hanged-Man-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Hanged Man'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/13-Death-Tarot-card-img-182x300-1.jpg.webp',
        name:'Death'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/14-Temperance-Tarot-card-img-182x300-1.jpg.webp',
        name:'Temperance'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/15-The-Devil-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Devil'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/16-The-Tower-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Tower'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/17-The-Star-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Star'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/18-The-Moon-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Moon'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/19-The-Sun-Tarot-card-img-182x300-1.jpg.webp',
        name:'The Sun'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/20-Judgment-Tarot-card-img-182x300-1.jpg.webp',
        name:'Judgement'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/21-The-World-Tarot-card-img-182x300-1.jpg.webp',
        name:'The World'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/01-ace-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Ace of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/02-two-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Two of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/03-three-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Three of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/04-four-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Four of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/05-five-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Five of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/06-six-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Six of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/07-seven-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Seven of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/08-eight-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Eight of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/09-nine-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Nine of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/09-nine-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Ten of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/10-page-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Page of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/11-knight-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Knight of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/12-queen-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'Queen of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/14-king-of-wands-tarot-card-img-182x300-1.jpg.webp',
        name:'King of Wands'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/01-ace-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Ace of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/02-two-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Two of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/03-three-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Three of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/04-four-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Four of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/05-five-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Five of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/06-six-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Six of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/07-seven-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Seven of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/08-eight-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Eight of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/09-nine-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Nine of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/10-ten-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Ten of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/11-page-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Page of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/12-knight-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Knight of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/13-queen-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'Queen of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/14-king-of-cups-tarot-card-img-182x300-1.jpg.webp',
        name:'King of Cups'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/01-ace-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Ace of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/02-two-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Two of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/03-three-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Three of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/04-four-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Four of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/05-five-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Five of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/06-six-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Six of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/07-seven-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Seven of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/08-eight-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Eight of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/09-nine-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Nine of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/10-ten-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Ten of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/11-page-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Page of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/12-knight-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Knight of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/13-queen-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'Queen of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/14-king-of-pentacles-tarot-card-img-182x300-1.jpg.webp',
        name:'King of Pentacles'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/01-ace-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Ace of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/02-two-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Two of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/03-three-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Three of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/04-four-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Four of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/05-five-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Five of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/06-six-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Six of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/07-seven-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Seven of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/08-eight-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Eight of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/09-nine-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Nine of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/10-ten-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Ten of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/11-page-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Page of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/12-knight-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Knight of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/13-queen-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'Queen of Swords'},
        {src:'https://www.purplegarden.co/blog/wp-content/uploads/2023/03/14-king-of-swords-tarot-card-img-182x300-1.jpg.webp',
        name:'King of Swords'}
]






